### ISSUE TITLE
Describe and implement 2D SRT LBM Collision operation

### ISSUE THREAD

**Issue by kks32** [cbgeo-archives/lbm-poiseuille#5]

**Comment by reihos** [comment]
f0_eq=4/9rho[1-3/(2c^2)*(Vx^2+Vy^2)]
f1_eq=1/9rho[1+3/c^2*Vx+9/(2c^2)*Vx^2-3/(2c^2)*(Vx^2+Vy^2)]
f2_eq=1/9rho[1+3/c^2*Vy+9/(2c^2)*Vy^2-3/(2c^2)*(Vx^2+Vy^2)]
f3_eq=1/9rho[1-3/c^2*Vx+9/(2c^2)*Vx^2-3/(2c^2)*(Vx^2+Vy^2)]
f4_eq=1/9rho[1-3/c^2*Vy+9/(2c^2)*Vy^2-3/(2c^2)*(Vx^2+Vy^2)]
f5_eq=1/36rho[1-3/c^2*(Vx+Vy)+9/(2c^2)*(Vx+Vy)^2-3/(2c^2)*(Vx^2+Vy^2)]
f6_eq=1/36rho[1-3/c^2*(-Vx+Vy)+9/(2c^2)*(-Vx+Vy)^2-3/(2c^2)*(Vx^2+Vy^2)]
f7_eq=1/36rho[1-3/c^2*(-Vx-Vy)+9/(2c^2)*(-Vx-Vy)^2-3/(2c^2)*(Vx^2+Vy^2)]
f8_eq=1/36rho[1-3/c^2*(Vx-Vy)+9/(2c^2)*(Vx-Vy)^2-3/(2c^2)*(Vx^2+Vy^2)]
